import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ReportOptions {
  activeTab: 'overview' | 'scores' | 'activity';
  reportData?: any;        // overview data
  scoresData?: any[];      // score audit rows
  auditData?: any[];       // activity log rows
  scoreFilters?: {        // active filters for scores tab
    userId?: string;
    from?: string;
    to?: string;
    limit?: number;
  };
  generatedBy?: string;    // admin name
  allTabs?: boolean;       // flag to render all three sections
}

export const generateReport = (options: ReportOptions) => {
  const {
    activeTab,
    reportData,
    scoresData,
    auditData,
    scoreFilters,
    generatedBy,
    allTabs = false
  } = options;

  const doc = new jsPDF();
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric'
  });
  const timeStr = now.toLocaleTimeString('en-IN');

  const renderHeader = (pageDoc: jsPDF) => {
    pageDoc.setFontSize(20);
    pageDoc.setFont('helvetica', 'bold');
    pageDoc.setTextColor(0);
    pageDoc.text('Golf Charity Platform', 14, 20);

    pageDoc.setFontSize(11);
    pageDoc.setFont('helvetica', 'normal');
    pageDoc.setTextColor(100);
    pageDoc.text('Admin Report', 14, 28);

    pageDoc.setFontSize(9);
    pageDoc.text(`Generated: ${dateStr} at ${timeStr}`, 14, 35);
    if (generatedBy) pageDoc.text(`Generated by: ${generatedBy}`, 14, 41);

    // Horizontal line
    pageDoc.setDrawColor(200);
    pageDoc.line(14, 45, 196, 45);
  };

  let yPos = 52;
  renderHeader(doc);

  // ── RENDER OVERVIEW ────────────────────────────────
  const renderOverview = (startPage = false) => {
    if (startPage) {
      doc.addPage();
      renderHeader(doc);
      yPos = 52;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Platform Overview Report', 14, yPos);
    yPos += 10;

    // User Stats table
    doc.setFontSize(11);
    doc.text('User Statistics', 14, yPos);
    yPos += 4;

    autoTable(doc, {
      startY: yPos,
      head: [['Metric', 'Value']],
      body: [
        ['Total Users', String(reportData?.users?.total ?? 0)],
        ['Active Subscribers', String(reportData?.users?.active ?? 0)],
        ['Inactive / Lapsed', String(
          (reportData?.users?.total ?? 0) - (reportData?.users?.active ?? 0)
        )],
      ],
      headStyles: { fillColor: [40, 40, 40] },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      margin: { left: 14 },
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;

    // Financial Stats table
    doc.text('Financial Summary', 14, yPos);
    yPos += 4;

    autoTable(doc, {
      startY: yPos,
      head: [['Metric', 'Value']],
      body: [
        ['Prize Pool Estimate', 
          '₹' + ((reportData?.financials?.prizePoolEstimate ?? 0) / 100).toLocaleString('en-IN')],
        ['Jackpot Amount', 
          '₹' + ((reportData?.financials?.jackpotAmount ?? 0) / 100).toLocaleString('en-IN')],
        ['Total Paid Out', 
          '₹' + Number(reportData?.financials?.totalWithdrawnPaid ?? 0).toLocaleString('en-IN')],
        ['Pending Withdrawals', 
          '₹' + Number(reportData?.financials?.totalWithdrawnPending ?? 0).toLocaleString('en-IN')],
      ],
      headStyles: { fillColor: [40, 40, 40] },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      margin: { left: 14 },
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;

    // Platform Stats table
    doc.text('Platform Statistics', 14, yPos);
    yPos += 4;

    autoTable(doc, {
      startY: yPos,
      head: [['Metric', 'Value']],
      body: [
        ['Total Published Draws', String(reportData?.draws?.total ?? 0)],
        ['Pending Winner Verifications', String(reportData?.winners?.pending ?? 0)],
        ['Next Draw Date', reportData?.nextDrawDate 
          ? new Date(reportData.nextDrawDate).toLocaleDateString('en-IN')
          : 'Not scheduled'],
      ],
      headStyles: { fillColor: [40, 40, 40] },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      margin: { left: 14 },
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;

    // Charity Distribution table
    if (reportData?.charityDistribution) {
      doc.text('Charity Distribution', 14, yPos);
      yPos += 4;

      const total = Object.values(
        reportData.charityDistribution as Record<string, number>
      ).reduce((a, b) => a + b, 0);

      const charityRows = Object.entries(
        reportData.charityDistribution as Record<string, number>
      )
        .sort((a, b) => b[1] - a[1])
        .map(([name, count]) => [
          name,
          String(count),
          total > 0 
            ? ((count / total) * 100).toFixed(1) + '%' 
            : '0%'
        ]);

      autoTable(doc, {
        startY: yPos,
        head: [['Charity Name', 'Subscribers', 'Share']],
        body: charityRows,
        headStyles: { fillColor: [40, 40, 40] },
        alternateRowStyles: { fillColor: [248, 248, 248] },
        margin: { left: 14 },
      });
      yPos = (doc as any).lastAutoTable.finalY + 10;
    }
  };

  // ── RENDER SCORES ──────────────────────────────────
  const renderScores = (startPage = false) => {
    if (startPage) {
      doc.addPage();
      renderHeader(doc);
      yPos = 52;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Score Audit Report', 14, yPos);
    yPos += 8;

    // Show active filters in PDF if any
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    if (scoreFilters?.userId) {
      doc.text(`Filtered by User ID: ${scoreFilters.userId}`, 14, yPos);
      yPos += 5;
    }
    if (scoreFilters?.from || scoreFilters?.to) {
      doc.text(
        `Date range: ${scoreFilters.from ?? 'any'} → ${scoreFilters.to ?? 'any'}`,
        14, yPos
      );
      yPos += 5;
    }
    doc.text(`Records shown: ${scoresData?.length ?? 0}`, 14, yPos);
    yPos += 8;

    doc.setTextColor(0);

    autoTable(doc, {
      startY: yPos,
      head: [['#', 'User Name', 'Email', 'Score', 'Date Played', 'Submitted']],
      body: (scoresData || []).map((s, i) => [
        String(i + 1),
        s.users?.name ?? '-',
        s.users?.email ?? '-',
        String(s.score),
        s.datePlayed 
          ? new Date(s.datePlayed).toLocaleDateString('en-IN') 
          : '-',
        s.createdAt 
          ? new Date(s.createdAt).toLocaleDateString('en-IN') 
          : '-',
      ]),
      headStyles: { fillColor: [40, 40, 40] },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      margin: { left: 14 },
      columnStyles: {
        3: { halign: 'center' }
      }
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;
  };

  // ── RENDER ACTIVITY ────────────────────────────────
  const renderActivity = (startPage = false) => {
    if (startPage) {
      doc.addPage();
      renderHeader(doc);
      yPos = 52;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text('Activity Log Report', 14, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(`Total events: ${auditData?.length ?? 0}`, 14, yPos);
    yPos += 8;
    doc.setTextColor(0);

    autoTable(doc, {
      startY: yPos,
      head: [['Type', 'Description', 'Date & Time']],
      body: (auditData || []).map(event => {
        let description = '';
        if (event.type === 'registration') 
          description = `${event.name ?? 'User'} registered`;
        else if (event.type === 'subscription') 
          description = `${event.name ?? 'User'} activated ${event.plan ?? ''} subscription`;
        else if (event.type === 'withdrawal') 
          description = `${event.name ?? 'User'} requested withdrawal of ₹${event.amount ?? 0}`;
        else if (event.type === 'draw') 
          description = `${event.month ?? ''} ${event.year ?? ''} draw published`;
        else 
          description = event.type;

        return [
          event.type.charAt(0).toUpperCase() + event.type.slice(1),
          description,
          event.createdAt 
            ? new Date(event.createdAt).toLocaleString('en-IN') 
            : '-'
        ];
      }),
      headStyles: { fillColor: [40, 40, 40] },
      alternateRowStyles: { fillColor: [248, 248, 248] },
      margin: { left: 14 },
    });
    yPos = (doc as any).lastAutoTable.finalY + 10;
  };

  // Execute rendering based on conditions
  if (allTabs) {
    renderOverview(false);
    renderScores(true);
    renderActivity(true);
  } else {
    if (activeTab === 'overview') renderOverview();
    else if (activeTab === 'scores') renderScores();
    else if (activeTab === 'activity') renderActivity();
  }

  // ── FOOTER ───────────────────────────────────────────
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount} · Golf Charity Platform · Confidential`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  // ── SAVE ─────────────────────────────────────────────
  const tabLabel = allTabs ? 'FullReport' : (
    activeTab === 'overview' ? 'Overview' :
    activeTab === 'scores' ? 'ScoreAudit' : 'ActivityLog'
  );

  const fileName = 
    `GolfPlatform_${tabLabel}_Report_` +
    `${now.toISOString().slice(0, 10)}.pdf`;

  doc.save(fileName);
};
